apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nebula-studio.fullname" . }}
  labels:
    {{- include "nebula-studio.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "nebula-studio.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nebula-studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nebula-studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: http-gateway
          image: "{{ .Values.image.httpGateway.repository }}:{{ .Values.image.httpGateway.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USER
              value: root
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {{- toYaml .Values.resources.httpGateway | nindent 12 }}
        - name: nebula-importer
          image: "{{ .Values.image.nebulaImporter.repository }}:{{ .Values.image.nebulaImporter.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5699
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /tasks
              port: 5699
          readinessProbe:
            httpGet:
              path: /tasks
              port: 5699
          resources:
            {{- toYaml .Values.resources.nebulaImporter | nindent 12 }}
          command:
            - nebula-importer
            - "--port=5699"
            - "--callback=http://127.0.0.1:7000/api/import/finish"
          volumeMounts:
            - name: {{ include "nebula-studio.fullname" . }}-upload-data
              mountPath: /uploads
        - name: nebula-studio
          image: "{{ .Values.image.nebulaStudio.repository }}:{{ .Values.image.nebulaStudio.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UPLOAD_DIR
              value: /uploads
          ports:
            - containerPort: 7001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7001
          readinessProbe:
            httpGet:
              path: /
              port: 7001
          command:
            - egg-scripts
            - start
            - --title=egg-server-nebula-graph-studio
            - --workers=3
          resources:
            {{- toYaml .Values.resources.nebulaStudio | nindent 12 }}
          volumeMounts:
            - name: {{ include "nebula-studio.fullname" . }}-upload-data
              mountPath: /uploads
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7000
          readinessProbe:
            httpGet:
              path: /
              port: 7000
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          volumeMounts:
            - name: {{ include "nebula-studio.fullname" . }}-upload-data
              mountPath: /uploads
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nebula.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nebula-studio.fullname" . }}-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "nebula-studio.fullname" . }}-upload-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistent.storageClassName }}
          storageClassName: {{ .Values.persistent.storageClassName  }}
        {{- end }}
        resources:
          requests:
          {{- if .Values.persistent.size }}
            storage: {{ .Values.persistent.size  }}
          {{- else }}
            storage: 5Gi
          {{- end }}